### ISSUE TITLE
Create a 1.0.0 release tag

### ISSUE THREAD

**Issue by simonwfarrow** [piotch/jQuery-QueryBuilder-Elasticsearch#9]
Hi,
Thanks for merging the bower.json, would it be possible for you to make a release with a 1.0.0 tag so I can pull from this repo from bower.
Thanks,
Simon

**Comment by piotch** [comment]
Hello, 
I created it, thank you. I named the tag "v1.0.0" following github suggestion, let me know if this works for you.
Pierre

**Comment by simonwfarrow** [comment]
Works perfectly, thank you vey much. And thanks for the lib, makes constructing elastic queries very easy.
Simon
